project:
  type: website
  output-dir: docs

website:
  title: "Mayank Jobanputra"
  site-url: "https://mayankjobanputra.github.io"
  description: "Personal website of Mayank Jobanputra"
  search: true

  navbar:
    right:
      - text: "Home"
        href: index.qmd
      - text: "Publications"
        href: publications.qmd
      - text: "Blogs"
        href: resources/blogs/blogs_home.qmd

format:
  html:
    theme:
      light: cosmo
      dark: darkly
#    css: styles.css
    toc: true

execute:
  freeze: auto